import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import "aos/dist/aos.css";
import { Figtree } from "@next/font/google";
// import { useEffect } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add weights you want to use
  variable: "--font-figtree",
});
// useEffect(() => {
//   AOS.init();
//   AOS.refresh();
// }, []);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
