import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import "aos/dist/aos.css";
// import { useEffect } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// useEffect(() => {
//   AOS.init();
//   AOS.refresh();
// }, []);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
